<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Lingyan.Demo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Lingyan.Core.Dotnet/Lingyan.Core.Dotnet.csproj" />
  </ItemGroup>

</Project>
